apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: etcd
    etcd_cluster: kube-etcd
  name: kube-etcd-backup-sidecar
  namespace: kube-system
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: etcd-backup
      etcd_cluster: kube-etcd
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: etcd-backup
        etcd_cluster: kube-etcd
    spec:
      containers:
      - command:
        - etcdbrctl
        - snapshot
        - --cacert=/root/tls/etcd-client-ca.crt
        - --cert=/root/tls/etcd-client.crt
        - --key=/root/tls/etcd-client.key
        - --schedule=*/10 * * * *
        - --max-backups=5
        - --endpoints=https://${service_ip}:2379
        - --storage-provider=S3
        - --store-container=${bucket}
        - --store-prefix=${prefix}
        image: ${backup_image}:${backup_version}
        imagePullPolicy: IfNotPresent
        name: backup
        resources: {}
        volumeMounts:
        - mountPath: /root/.aws/
          name: secret
        - mountPath: /root/tls/
          name: etcd-tls
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - name: secret
        secret:
          defaultMode: 420
          secretName: etcd-backup
      - name: etcd-tls
        secret:
          defaultMode: 420
          secretName: etcd-client-tls

