#
# namespace
#
apiVersion: v1
kind: Namespace
metadata:
  name: kube-lego
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoheaders
  namespace: kube-lego
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: echoheaders
    spec:
      containers:
      - name: echoheaders
        image: gcr.io/google_containers/echoserver:1.8
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: echoheaders
  namespace: kube-lego
  labels:
    app: echoheaders
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: echoheaders
---
# This is the Ingress resource that creates a HTTP Loadbalancer configured
# according to the Ingress rules.
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
     kubernetes.io/tls-acme: "true"
     kubernetes.io/ingress.class: "nginx"
  name: echomap
  namespace: kube-lego
spec:
  tls:
    - hosts:
        - lego.${ingress}
      secretName: echoserver-tls

  rules:
  - host: lego.${ingress}
    http:
      paths:
      - path: /
        backend:
          serviceName: echoheaders
          servicePort: 80
