# Copyright 2017 The Gardener Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

##############################################################################
# openstack iaas configuration handling
# pack or unpack configuration variables for iaas layer
# generated by create.sh based on variables.tf
##############################################################################

#
# specify config map to unpack settings into output
#
variable "iaas_config" {
  type = "map"
  default = { }
}

#
# or specify variables according to variables.tf to
# pack a config map
#

module "user_name" {
  source="../../../../modules/variable"
  value="${lookup(var.iaas_config,"user_name",var.user_name)}"
}
module "availability_zone" {
  source="../../../../modules/variable"
  value="${lookup(var.iaas_config,"availability_zone",var.availability_zone)}"
}
module "tenant_name" {
  source="../../../../modules/variable"
  value="${lookup(var.iaas_config,"tenant_name",var.tenant_name)}"
}
module "domain_name" {
  source="../../../../modules/variable"
  value="${lookup(var.iaas_config,"domain_name",var.domain_name)}"
}
module "password" {
  source="../../../../modules/variable"
  value="${lookup(var.iaas_config,"password",var.password)}"
}
module "auth_url" {
  source="../../../../modules/variable"
  value="${lookup(var.iaas_config,"auth_url",var.auth_url)}"
}
module "region" {
  source="../../../../modules/variable"
  value="${lookup(var.iaas_config,"region",var.region)}"
}
module "insecure" {
  source="../../../../modules/variable"
  value="${lookup(var.iaas_config,"insecure",var.insecure)}"
}
module "fip_pool_name" {
  source="../../../../modules/variable"
  value="${lookup(var.iaas_config,"fip_pool_name",var.fip_pool_name)}"
}
module "lbaas_subnet_id" {
  source="../../../../modules/variable"
  value="${lookup(var.iaas_config,"lbaas_subnet_id",var.lbaas_subnet_id)}"
}
module "lbaas_pool_name" {
  source="../../../../modules/variable"
  value="${lookup(var.iaas_config,"lbaas_pool_name",var.lbaas_pool_name)}"
}
module "lbaas_provider" {
  source="../../../../modules/variable"
  value="${lookup(var.iaas_config,"lbaas_provider",var.lbaas_provider)}"
}

#
# always provide a config map value
#
output "iaas_config" {
  value = {
    user_name = "${module.user_name.value}"
    availability_zone = "${module.availability_zone.value}"
    tenant_name = "${module.tenant_name.value}"
    domain_name = "${module.domain_name.value}"
    password = "${module.password.value}"
    auth_url = "${module.auth_url.value}"
    region = "${module.region.value}"
    insecure = "${module.insecure.value}"
    fip_pool_name = "${module.fip_pool_name.value}"
    lbaas_subnet_id = "${module.lbaas_subnet_id.value}"
    lbaas_pool_name = "${module.lbaas_pool_name.value}"
    lbaas_provider = "${module.lbaas_provider.value}"
  }
}

#
# always provide all settings as dedicated output
#
output "user_name" {
  value = "${module.user_name.value}"
}
output "availability_zone" {
  value = "${module.availability_zone.value}"
}
output "tenant_name" {
  value = "${module.tenant_name.value}"
}
output "domain_name" {
  value = "${module.domain_name.value}"
}
output "password" {
  value = "${module.password.value}"
}
output "auth_url" {
  value = "${module.auth_url.value}"
}
output "region" {
  value = "${module.region.value}"
}
output "insecure" {
  value = "${module.insecure.value}"
}
output "fip_pool_name" {
  value = "${module.fip_pool_name.value}"
}
output "lbaas_subnet_id" {
  value = "${module.lbaas_subnet_id.value}"
}
output "lbaas_pool_name" {
  value = "${module.lbaas_pool_name.value}"
}
output "lbaas_provider" {
  value = "${module.lbaas_provider.value}"
}
