# Copyright (c) 2017 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

##############################################################################
# iaas access configuration handling
# generated by ../create.sh based on local variables.tf
##############################################################################

#
# specify config map to unpack settings into output
#
variable "defaults" {
  type = "map"
  default = { 
  }
}
variable "access_info" {
  type = "map"
  default = { }
}

#
# or specify variables according to variables.tf to
# pack a config map
#

locals {
  info = "${merge(var.defaults,var.access_info)}"

  secret_key = "${var.secret_key == "" ? lookup(local.info,"secret_key",var.secret_key) : var.secret_key}"
  access_key = "${var.access_key == "" ? lookup(local.info,"access_key",var.access_key) : var.access_key}"
  region = "${var.region == "" ? lookup(local.info,"region",var.region) : var.region}"
}


output "access_info" {
  value = {
      secret_key = "${local.secret_key}"
      access_key = "${local.access_key}"
      region = "${local.region}"
  }
}

#
# always provide all settings as dedicated output
#
output "secret_key" {
  value = "${local.secret_key}"
}
output "access_key" {
  value = "${local.access_key}"
}
output "region" {
  value = "${local.region}"
}
