# Copyright (c) 2017 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

##############################################################################
# iaas access configuration handling
# generated by ../create.sh based on local variables.tf
##############################################################################

#
# specify config map to unpack settings into output
#
variable "defaults" {
  type = "map"
  default = {
  }
}
variable "access_info" {
  type = "map"
  default = { }
}

#
# or specify variables according to variables.tf to
# pack a config map
#

locals {
  info = "${merge(var.defaults,var.access_info)}"

  client_id = "${var.client_id == "" ? lookup(local.info,"client_id",var.client_id) : var.client_id}"
  client_secret = "${var.client_secret == "" ? lookup(local.info,"client_secret",var.client_secret) : var.client_secret}"
  tenant_id = "${var.tenant_id == "" ? lookup(local.info,"tenant_id",var.tenant_id) : var.tenant_id}"
  subscription_id = "${var.subscription_id == "" ? lookup(local.info,"subscription_id",var.subscription_id) : var.subscription_id}"
  region = "${var.region == "" ? lookup(local.info,"region",var.region) : var.region}"
}


output "access_info" {
  value = {
      client_id = "${local.client_id}"
      client_secret = "${local.client_secret}"
      tenant_id = "${local.tenant_id}"
      subscription_id = "${local.subscription_id}"
      region = "${local.region}"
  }
}

#
# always provide all settings as dedicated output
#
output "client_id" {
  value = "${local.client_id}"
}
output "client_secret" {
  value = "${local.client_secret}"
}
output "tenant_id" {
  value = "${local.tenant_id}"
}
output "subscription_id" {
  value = "${local.subscription_id}"
}
output "region" {
  value = "${local.region}"
}
