apiVersion: v1
data:
  ca.crt: "${controller_manager_ca_crt_b64}"
  ca.key: "${controller_manager_ca_key_b64}"
  service-account.key: "${service_account_key_b64}"
kind: Secret
metadata:
  name: kube-controller-manager
  namespace: kube-system
type: Opaque
